# Generated by Django 4.0.2 on 2022-03-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_pledge_supporter_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('1 drink', '1 DRINK'), ('2 drink', '2 DRINK'), ('3 drink', '3 DRINK'), ('4 drink', '4 DRINK'), ('5+ drink', '5+ DRINK')], default='1 Drink', max_length=8),
        ),
    ]
