# Generated by Django 4.0.2 on 2022-05-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('1drink', '1DRINK'), ('2drink', '2DRINK'), ('3drink', '3DRINK'), ('4drink', '4DRINK'), ('5+drink', '5+DRINK')], default='1Drink', max_length=8),
        ),
    ]
